require("dotenv").config();
const express    = require("express");
const cors       = require("cors");
const morgan     = require("morgan");
const { getDb }        = require("./src/db/init");
const authRoutes       = require("./src/routes/auth");
const usersRoutes      = require("./src/routes/users");
const groupsRoutes     = require("./src/routes/groups");
const scheduleRoutes   = require("./src/routes/schedule");
const swapsRoutes      = require("./src/routes/swaps");
const reportsRoutes    = require("./src/routes/reports");
const meetingRoutes   = require('./src/routes/meeting');
const occurrencesRoutes = require('./src/routes/occurrences');
const absencesRoutes   = require("./src/routes/absences");
require("./src/sync-cron");
const app  = express();
const PORT = process.env.PORT || 3001;
app.use(cors({ origin: process.env.CORS_ORIGIN || "*" }));
app.use(express.json({ limit: "50mb" }));
app.use(morgan("dev"));
app.use((req, res, next) => { getDb(); next(); });
app.get("/health", (req, res) => res.json({ status: "ok", ts: new Date().toISOString() }));
app.use("/api/auth",     authRoutes);
app.use("/api/users",    usersRoutes);
app.use("/api/groups",   groupsRoutes);
app.use("/api/schedule", scheduleRoutes);
app.use("/api/swaps",    swapsRoutes);
app.use("/api/reports",  reportsRoutes);
const holidaysRoutes = require('./src/routes/holidays');
app.use("/api/holidays", holidaysRoutes);
app.use("/api/occurrences", occurrencesRoutes);
app.use("/api/meeting",  meetingRoutes);
app.use("/api/absences", absencesRoutes);
const vacationsRoutes = require("./src/routes/vacations");
app.use("/api/vacations", vacationsRoutes);
const pontoRoutes = require("./src/routes/ponto");
app.use("/api/ponto", pontoRoutes);
const batidasRoutes = require("./src/routes/batidas");
const notificationsRoutes = require("./src/routes/notifications");
app.use("/api/batidas", batidasRoutes);
app.use("/api/notifications", notificationsRoutes);
const muralRoutes = require("./src/routes/mural");
const formsRoutes = require("./src/routes/forms");
app.use("/api/mural", muralRoutes);
app.use("/api/forms", formsRoutes);
const documentsRoutes = require("./src/routes/documents");
app.use("/api/documents", documentsRoutes);
app.use("/api/indicators", require("./src/routes/indicators"));
app.use("/api/internal", require("./src/routes/internal"));
app.use((err, req, res, next) => { console.error(err); res.status(500).json({ error: "Erro interno" }); });
app.listen(PORT, () => console.log(`\n✅  ShiftSync API em http://localhost:${PORT}\n`));
